language: rust
cache: cargo

matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-gnu

env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - PROJECT_NAME=soundsense-rs

before_install:
  - if [[ $TRAVIS_OS_NAME = linux]]; then sudo apt-get install alsa; fi
  
install:
  - if [[ $TRAVIS_OS_NAME = linux && $HOST != $TARGET ]]; then rustup target add $TARGET; fi

script:
  - cargo build --target $TARGET --verbose

before_deploy:
  - bash ci/before_deploy.bash

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file:
    -$PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
    -$PROJECT_NAME*.deb
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable && $TARGET != ""

notification:
  email:
    on_succes: never
