language: rust
cache: cargo
rust:
- stable

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- osx
- windows

script:
  - cargo build --verbose --release

before_deploy:
- if [[ -f target/release/soundsense-rs ]]; then mv target/release/soundsense-rs "target/release/soundsense-rs-$TRAVIS_TAG-$TRAVIS_OS_NAME"

deploy:
- provider: releases
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"
  file:
  - target/release/soundsense-rs-*
  api_key:
    secure: dIgazBfesIuLdougBNRu/nNwpqc+/2FLkxKAVWmk5gY2E3PmjPbrq0OMc5MkqnmZodV+0vvatjzTJxqsGMNmw4WwWZie76z6e4sWcgNpM/Ce84u0gN6+FSClecE77saQpdgjA8KJxrRD3dQC/unFGQSCfuk6Omlk3ES3Ys7RFWeD1EPLvK8iybCKI42sQ9+ogZQ+3K9EqY3cjxynGcQr8Aqh6tBCx2xF2A5ZAybGJ3qlitgX7ZHOSuOnMWT5rDQrKDnzcPqMpzwZG3QYDiWOq8cF7mmrMVGJpsn4IqqmFMBYu8nxVNaoVXUgObKpr27DwscAI2dp+w0RWYmp9iN7DIGHYyYEkSukCFO1q/wJrg0+s/eicMX/fm/xH6FJZCM96ICSDG0tzvjESKW60RZbvd0dxDWsNx/pA3eSxYR1zKeVCI0ZJ5Z94TqAeQME6tXBcoSbB9IejH6FsN6ekzkgjfIoajmIabG/LJ1wSIleOtQ+sHdvyi7i26bp9clZIaaXf1ETWd0leRL+tESxvChf3mOzEjcDG85RGOaRfrcRAbAe/J/6E51m478kaWt+s3YAcVBEa/d8A7THrRZgkKsQCJsbT05s6l23NIeVpDiPL536tAcSwWMVabvdqXadoV7SkxIiGpyzYie0KbpulPapq0aspfTElmIYRnK4KvP7low=