[package]
name = "soundsense-rs"
version = "0.1.0"
authors = ["pc <paraxite@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyfiledialogs = {path = "tinyfiledialogs"}
notify = "4.0"
regex = "1.2"
rodio = "0.9"
xml-rs = "0.8"
winit = "0.20.0-alpha2"
conrod = {version = "0.61", features = ["winit", "glium"]}
rand = "0.7"