[package]
name = "soundsense-rs"
version = "0.1.0"
authors = ["pc <paraxite@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0"
regex = "1.2"
rodio = "0.9"
xml-rs = "0.8"
rand = "0.7"
gtk = {version ="0.7.0", features=["v3_16"]}
gio = {version = "0.7.0", features=["v2_44"]}
gdk = "*"
glib = {version = "0.8.0"}
lazy_static = "*"