[package]
name = "soundsense-rs"
version = "1.1.0"
authors = ["pc <paraxite@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0"
regex = "1.2"
rodio = "0.9"
xml-rs = "0.8"
rand = "0.7"
lazy_static = "*"
web-view = "0.4.1"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
getopts = "0.2"