# ToDo:
#   https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=powershell#setting-an-output-parameter
#   https://github.com/wraithan/cargo-bump
#   Split builders.

name: Release a new version

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    branches:
      - master
    types:
      - closed

permissions: write-all

jobs:
  merged_build:
    name: Merged build
    if: github.event.pull_request.merged
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure user
        run: |
          git config --global user.name "GitHub Workflow Runner"
          git config --global user.email "runner@github.azure"
      
      - name: Get bump tag
        run: |
          $COMMIT_MESSAGE = (git show --no-patch --pretty=%s%n%b)
          $GUID = (New-Guid).Guid
          Add-Content -Path $env:GITHUB_ENV -Value "COMMIT_MESSAGE<<${GUID}"
          foreach ($line in $COMMIT_MESSAGE) {
            Add-Content -Path $env:GITHUB_ENV -Value $line
          }
          Add-Content -Path $env:GITHUB_ENV -Value $GUID
          if       ($COMMIT_MESSAGE -match '!major') {
            $BUMP_TAG = 'major'
          } elseif ($COMMIT_MESSAGE -match '!minor') {
            $BUMP_TAG = 'minor'
          } elseif ($COMMIT_MESSAGE -match '!patch') {
            $BUMP_TAG = 'patch'
          } else {Exit(1)}
          Add-Content -Path $env:GITHUB_ENV -Value "BUMP_TAG=${BUMP_TAG}"
      
      - name: Bump version
        run: |
          cargo install cargo-edit
          cargo set-version --bump $env:BUMP_TAG
          $PATTERN = '(?s)\[package\].*?version = "(\d\.\d\.\d)"'
          Add-Content -Path $env:GITHUB_ENV -Value ('VERSION_STRING=' + "v$((Get-Content -Raw -Path ./Cargo.toml | Select-String -Pattern ${PATTERN}).Matches.Groups[1].Value)")
      
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: Update
        run: cargo update
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Package
        run: |
          $EXTENSION = ('${{runner.os}}' -eq 'Windows') ? '.exe' : ''
          New-Item -ItemType Directory -Path ./artifacts/; 
          Compress-Archive -Path "./target/release/soundsense-rs${EXTENSION}" -DestinationPath ("./artifacts/soundsense-rs-${env:VERSION_STRING}-${{runner.os}}.zip")
      
      - name: Commit
        if: runner.os == 'Linux'
        run: |
          git add Cargo.toml
          git commit -m ("Automated version bump to ${env:VERSION_STRING}")
      
      - name: Push commit
        if: runner.os == 'Linux'
        run: git push
        
      - name: Tag
        if: runner.os == 'Linux'
        run: git tag $env:VERSION_STRING
      
      - name: Push tag
        if: runner.os == 'Linux'
        run: git push origin $env:VERSION_STRING
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{env.VERSION_STRING}}
          body: ${{env.COMMIT_MESSAGE}}
          files: ./artifacts/*
