name: Release a new version

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merged_build:
    name: Merged build
    if: github.event.pull_request.merged
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get bump tag
        run: |
          echo 'debug1>'
          git show --no-patch --pretty=%s%n%b
          echo '<debug1'
          echo 'debug2>'
          [Environment]::SetEnvironmentVariable('COMMIT_MESSAGE', (git show --no-patch --pretty=%s%n%b), [EnvironmentVariableTarget]::User)
          echo '<debug2'
          [Environment]::GetEnvironmentVariable('COMMIT_MESSAGE', [EnvironmentVariableTarget]::User)
          if ([Environment]::GetEnvironmentVariable('COMMIT_MESSAGE', [EnvironmentVariableTarget]::User) -match '!major') {
            [Environment]::SetEnvironmentVariable('BUMP_TAG', 'major', [EnvironmentVariableTarget]::User)
          } elseif ([Environment]::GetEnvironmentVariable('COMMIT_MESSAGE', [EnvironmentVariableTarget]::User) -match '!minor') {
            [Environment]::SetEnvironmentVariable('BUMP_TAG', 'minor', [EnvironmentVariableTarget]::User)
          } elseif ([Environment]::GetEnvironmentVariable('COMMIT_MESSAGE', [EnvironmentVariableTarget]::User) -match '!patch') {
            [Environment]::SetEnvironmentVariable('BUMP_TAG', 'patch', [EnvironmentVariableTarget]::User)
          } else {Exit(1)}
      
      - name: Bump version
        run: |
          cargo install cargo-edit
          cargo set-version --bump (Get-Content -Path Env:BUMP_TAG)
          [Environment]::SetEnvironmentVariable('VERSION_STRING', ('v' + (Get-Content -Raw .\cargo.toml | Select-String -Pattern '(?s)\[package\].*?version = "(\d\.\d\.\d)"').Matches.Groups[1].Value), [EnvironmentVariableTarget]::User)
      
      - name: Update
        run: cargo update
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Package
        run: |
          New-Item -ItemType Directory -Path ./artifacts/; 
          Compress-Archive -Path './target/release/*' -DestinationPath './artifacts/soundsense-rs-' + (Get-Content -Path Env:VERSION_STRING) + '-${{runner.os}}.zip'
      
      - name: Commit
        run: |
          git add cargo.toml
          git commit -m ("Automated version bump to " + (Get-Content -Path Env:VERSION_STRING))
      
      - name: Tag
        run: git tag (Get-Content -Path Env:VERSION_STRING)
      
      - name: Push back
        run: git push --tags
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
