name: Release a new version

defaults:
  run:
    shell: pwsh

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merged_build:
    name: Merged build
    if: github.event.pull_request.merged
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    
    steps:
      - name: Debug
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
          ENV_CONTEXT: ${{toJson(env)}}
          JOB_CONTEXT: ${{toJson(job)}}
          STEPS_CONTEXT: ${{toJson(steps)}}
          RUNNER_CONTEXT: ${{toJson(runner)}}
          INPUTS_CONTEXT: ${{toJson(inputs)}}
        run: |
          echo 'GITHUB_CONTEXT:' + $env:GITHUB_CONTEXT
          echo 'ENV_CONTEXT:' + $env:ENV_CONTEXT
          echo 'JOB_CONTEXT:' + $env:JOB_CONTEXT
          echo 'STEPS_CONTEXT:' + $env:STEPS_CONTEXT
          echo 'RUNNER_CONTEXT:' + $env:RUNNER_CONTEXT
          echo 'INPUTS_CONTEXT:' + $env:INPUTS_CONTEXT
      
      - name: If patch
        if: contains(github.event.head_commit.message, '!patch')
        run: echo 'patch' > ./bump.tag
      
      - name: If minor
        if: contains(github.event.head_commit.message, '!minor')
        run: echo 'minor' > ./bump.tag
      
      - name: If major
        if: contains(github.event.head_commit.message, '!major')
        run: echo 'major' > ./bump.tag
      
      - name: Read bump tag
        run: |
          echo ((Test-Path ./bump.tag) ? (Get-Content ./bump.tag) : '::setFailed')
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}
      
      - name: Bump version
        run: |
          cargo install cargo-edit
          cargo set-version --bump (Get-Content -Path './bump.tag')
          'v' + (Get-Content -Raw .\cargo.toml | Select-String -Pattern '(?s)\[package\].*?version = "(\d\.\d\.\d)"').Matches.Groups[1].Value > ./bump.tag
      
      - name: Update
        run: cargo update
      
      - name: Build
        run: cargo build --release --verbose
      
      - name: Package
        run: |
          New-Item -ItemType Directory -Path ./artifacts/; 
          Compress-Archive -Path './target/release/*' -DestinationPath './artifacts/soundsense-rs-' + (Get-Content -Path './version.string') + '-${{runner.os}}.zip'
      
      - name: Commit
        run: |
          git add cargo.toml
          git commit -m ("Automated version bump to " + (Get-Content -Path './version.string'))
      
      - name: Tag
        run: git tag (Get-Content -Path './version.string')
      
      - name: Push back
        run: git push --tags
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
