on:
  push:
    tags-ignore:
      - 'v*'

name: Build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libasound2-dev libgtk-3-dev libwebket2gtk-4.0-dev
      
      # - name: Install dependencies (MacOS)
      #   if: runner.os == 'macOS'
      
      # - name: Install dependencies (Windows)
      #   if: runner.os == 'Windows'
      
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release