name: Build

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libasound2-dev libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
