name: Release a new version

on:
  pull_request:
    branches: [$default-branch]
    types:
      - closed

jobs:
  merged_build:
    name: Merged build
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: If patch
        if: contains(github.event.head_commit.message, '!patch')
        shell: pwsh
        run: echo 'patch' > ./bump.tag
      - name: If minor
        if: contains(github.event.head_commit.message, '!minor')
        shell: pwsh
        run: echo 'minor' > ./bump.tag
      - name: If major
        if: contains(github.event.head_commit.message, '!major')
        shell: pwsh
        run: echo 'major' > ./bump.tag
      - name: Update, build, tag and push back
        shell: pwsh
        run: |
          cargo install cargo-edit
          cargo set-version --bump (Get-Content -Path './bump.tag')
          'v' + (Get-Content -Raw .\cargo.toml | Select-String -Pattern '(?s)\[package\].*?version = "(\d\.\d\.\d)"').Matches.Groups[1].Value > ./bump.tag
          cargo update
          cargo build --release --verbose
          New-Item -ItemType Directory -Path ./artifacts/
          Compress-Archive -Path './target/release/*' -DestinationPath ./artifacts/soundsense-rs-(Get-Content -Path './version.string')-${{runner.os}}.zip
          git add cargo.toml
          git commit -m ("Automated version bump to " (Get-Content -Path './version.string'))
          git tag (Get-Content -Path './version.string')
          git push --tags
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
